// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIcBTyE4LGM7p6ieW4RlEefgBIxNn1mHU',
    appId: '1:967955530198:web:5652043511fabff96be477',
    messagingSenderId: '967955530198',
    projectId: 'fluttercourse-541dd',
    authDomain: 'fluttercourse-541dd.firebaseapp.com',
    storageBucket: 'fluttercourse-541dd.appspot.com',
    measurementId: 'G-1P21KWLRCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvUXD-OE8_l9E5ix2E0GCZORTxzfW8RNw',
    appId: '1:967955530198:android:3d31d0c03ecc63d66be477',
    messagingSenderId: '967955530198',
    projectId: 'fluttercourse-541dd',
    storageBucket: 'fluttercourse-541dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvXwakfqdHBzktGMZZHQmdp8d3pTdzc2w',
    appId: '1:967955530198:ios:982f055178c443006be477',
    messagingSenderId: '967955530198',
    projectId: 'fluttercourse-541dd',
    storageBucket: 'fluttercourse-541dd.appspot.com',
    iosClientId: '967955530198-jsl8c8uopcs2ncd0dnu6j3eejmgmk5bd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttercourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvXwakfqdHBzktGMZZHQmdp8d3pTdzc2w',
    appId: '1:967955530198:ios:982f055178c443006be477',
    messagingSenderId: '967955530198',
    projectId: 'fluttercourse-541dd',
    storageBucket: 'fluttercourse-541dd.appspot.com',
    iosClientId: '967955530198-jsl8c8uopcs2ncd0dnu6j3eejmgmk5bd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttercourse',
  );
}
